name: reflection_factory
description: Allows Dart reflection with an easy approach, even for third-party classes, using code generation portable for all Dart platforms.
version: 2.2.7
homepage: https://github.com/gmpassos/reflection_factory

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.1
  analyzer: ^6.2.0
  dart_style: ^2.3.4
  meta: ^1.9.1
  mime: ^1.0.4
  base_codecs: ^1.0.1
  pub_semver: ^2.1.4
  path: ^1.8.3
  collection: ^1.18.0
  yaml: ^3.1.2
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^2.2.2
  lints: ^3.0.0
  pubspec: ^2.3.0
  data_serializer: ^1.0.12
  dependency_validator: ^3.2.2
  test: ^1.24.9
  coverage: ^1.7.2
  benchmark: ^0.3.0
