name: reflection_factory
description: Allows Dart reflection with an easy approach, even for third-party classes, using code generation portable for all Dart platforms.
version: 2.3.3
homepage: https://github.com/gmpassos/reflection_factory

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.1
  analyzer: ^6.4.1
  dart_style: ^2.3.6
  meta: ^1.14.0
  mime: ^1.0.5
  base_codecs: ^1.0.1
  pub_semver: ^2.1.4
  path: ^1.9.0
  collection: ^1.18.0
  yaml: ^3.1.2
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.9
  build_test: ^2.2.2
  lints: ^3.0.0
  pubspec: ^2.3.0
  data_serializer: ^1.1.0
  dependency_validator: ^3.2.3
  test: ^1.25.2
  coverage: ^1.7.2
  benchmark: ^0.3.0
